serviceName: "consumer-frontend"
replicas: 1
image:
  name: "bacehub/consumer-frontend"
  tag: "latest"
  pullSecret: docker-bacehub
port: 80

# serviceName: ""
# replicas: 1
# image:
#   name: "blabla"
#   tag: ""
#   pullSecret: ""
# port: 3000
livenessProbe: {}
readinessProbe: {}
env: {}
db:
  enabled: false
  instances: 1
  size: 5Gi
  database: ""
  owner: ""
  affinity: {}
  # initdb: {}
  # clusterSpec: {} # https://cloudnative-pg.io/documentation/1.19/cloudnative-pg.v1/#postgresql-cnpg-io-v1-ClusterSpec
ingress:
  enabled: true
  host: "consumer.staging.bacehub.de"
  annotations: {}
