name: ""
kind: Deployment
replicas: 1
image:
  name: ""
  tag: ""
  pullSecret: ""
port: 3000
livenessProbe: {}
readinessProbe: {}
env: {}
envOverride: {}
db:
  injectEnv: false
  envPrefix: "DATABASE"
  enabled: false
  instances: 1
  size: 5Gi
  database: ""
  owner: ""
  affinity: {}
  initdb: {}
  clusterSpec: {} # https://cloudnative-pg.io/documentation/1.19/cloudnative-pg.v1/#postgresql-cnpg-io-v1-ClusterSpec
migration: {}
ingress:
  enabled: false
  host: ""
  annotations: {}
