replicaCount: 1

kind: "Deployment"

revision: "latest"
image:
  repository: nginx
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: false
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

envFrom: []

sidecar: []

service:
  enabled: true
  type: ClusterIP
  port: 3000
  name: http
  extraPorts: []

resources: {}

livenessProbe:
  timeoutSeconds: 2
  initialDelaySeconds: 3
  httpGet:
    path: /health
    port: 3000
readinessProbe:
  timeoutSeconds: 2
  initialDelaySeconds: 3
  httpGet:
    path: /health
    port: 3000

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
