nameOverride: ""
fullnameOverride: ""

replicaCount: 1
kind: "Deployment"
revision: "latest"
image:
  repository: nginx
  pullPolicy: IfNotPresent

imagePullSecrets: []
env: []
envFrom: []
sidecar: []
service:
  enabled: true
  type: ClusterIP
  port: 3000
  name: http
  extraPorts: []

rabbitmq:
  enabled: false
  user: user
  secretName: rabbitmq-auth
  passwordKey: rabbitmq-password
  host: rabbitmq.rabbitmq.svc.cluster.local
  port: 5672

ingress:
  enabled: false
  entryPoints:
    - websecure
  match: Host(`replaceme.com`)
  extraRoutes: []

resources: {}

livenessProbe:
  timeoutSeconds: 2
  initialDelaySeconds: 3
  httpGet:
    path: /health
    port: 3000
readinessProbe:
  timeoutSeconds: 2
  initialDelaySeconds: 3
  httpGet:
    path: /health
    port: 3000

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
serviceAccount:
  create: false
  automount: false
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
