fullnameOverride: galactus
envFrom:
- configMapRef:
    name: app-config
revision: "production"
image:
  repository: ghcr.io/example/super-app
imagePullSecrets:
- name: docker-pullsecret

env:
- name: BINGO_SERVICE_URL
  value: bingo.bingo.svc.cluster.local

service:
  extraPorts:
  - name: grpc
    port: 50051

sidecar:
- name: logging-sidecar
  image: busybox
  command: ["sh", "-c", "tail -f /var/log/app.log"]
  volumeMounts:
    - name: logs
      mountPath: /var/log

rabbitmq:
  enabled: true
  user: user
  secretName: rabbitmq-auth
  passwordKey: rabbitmq-password
  host: rabbitmq.rabbitmq.svc.cluster.local
  port: 5672

ingress:
  enabled: true
  entryPoints:
    - websecure
  match: Host(`app.example.com`)
  extraRoutes:
  - match: Host(`app.example.com`) && PathPrefix(`/api`)
    kind: Rule
    services:
    - name: galactus
      port: 50051
