{{ if and .Values.ingress.enabled .Values.port -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.name }}
  annotations:
    kubernetes.io/ingress.class: traefik
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  entryPoints:
   - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.ingress.host }}`)
    {{- if .Values.ingress.middlewares }}
    middlewares:
    {{- range .Values.ingress.middlewares }}
    - name: {{ .name }}
    {{- end }}
    {{- end }}
    services:
      - name: {{ .Values.name }}
        passHostHeader: true
        port: {{ .Values.port }}
{{ end -}}
