{{/* Main application deployment */}}
apiVersion: apps/v1
kind: {{ .Values.kind }}
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.name }}
        app.kubernetes.io/component: application
    spec:
      restartPolicy: Always
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if and .Values.db.enabled .Values.waitDb }}
        - name: wait-for-postgres
          image: postgres:16
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-pg-app
                  key: uri
          command: ["sh", "-c"]
          args:
            - >
              until pg_isready -d "$DATABASE_URL"; do
                echo "Waiting for PostgreSQL to be ready...";
                sleep 5;
              done;
        {{- end }}
        {{- if .Values.initContainers }}
        {{- toYaml .Values.initContainers | nindent 8 }}
        {{- end }}
      {{- if not (or (and .Values.db.enabled .Values.waitDb) .Values.initContainers) }}
      initContainers: []
      {{- end }}
      {{- if .Values.volumes }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.name }}:{{ default (default "latest" .Values.revision) .Values.image.tag }}"
          imagePullPolicy: {{ if eq (default (default "latest" .Values.revision) .Values.image.tag) "latest" }}Always{{ else }}IfNotPresent{{ end }}
          {{- if .Values.livenessProbe }}
          livenessProbe: {{ .Values.livenessProbe | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe: {{ .Values.readinessProbe | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.port}}
          ports:
            - containerPort: {{ .Values.port }}
          {{- end }}
          {{- if .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          {{- end }}
          {{- with .Values.containerSpec }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- if or .Values.env .Values.db.injectEnv .Values.ingress.enabled .Values.envOverride .Values.envFrom }}
          {{- if .Values.envFrom }}
          envFrom:
            {{- toYaml .Values.envFrom | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.ingress.enabled }}
            - name: HOSTNAME
              value: {{ .Values.ingress.host }}
            {{- end }}
            {{- if .Values.db.injectEnv }}
            - name: {{ .Values.db.envPrefix }}_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-pg-app
                  key: uri
            - name: {{ .Values.db.envPrefix }}_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-pg-app
                  key: username
            - name: {{ .Values.db.envPrefix }}_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-pg-app
                  key: password
            - name: {{ .Values.db.envPrefix }}_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-pg-app
                  key: host
            - name: {{ .Values.db.envPrefix }}_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-pg-app
                  key: port
            - name: {{ .Values.db.envPrefix }}_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-pg-app
                  key: dbname
            {{- end }}
            {{- if .Values.env }}
            {{- .Values.env | toYaml | nindent 12 }}
            {{- end }}
            {{- if .Values.envOverride }}
            {{- .Values.envOverride | toYaml | nindent 12 }}
            {{- end }}
          {{- end }}
