{{- if .Values.db.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}-pg
spec:
  instances: {{ .Values.db.instances }}
  storage:
    size: {{ .Values.db.size }}
    storageClass: local-path
  {{- if .Values.db.backup }}
  backup: {{ .Values.db.backup | toYaml | nindent 4 }}
  {{- end }}
  bootstrap:
    initdb:
      database: {{ .Values.db.database }}
      owner: {{ .Values.db.owner }}
      {{- with .Values.db.initdb }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  {{- with .Values.db.clusterSpec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- if .Values.db.affinity }}
  affinity: {{ .Values.db.affinity | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
