apiVersion: apps/v1
kind: {{ .Values.kind }}
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.name }}
        app.kubernetes.io/component: application
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ if eq .Values.image.tag "latest" }}Always{{ else }}IfNotPresent{{ end }}
          {{- if .Values.livenessProbe }}
          livenessProbe: {{ .Values.livenessProbe | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe: {{ .Values.readinessProbe | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.port}}
          ports:
            - containerPort: {{ .Values.port }}
          {{- end }}
          {{- with .Values.containerSpec }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- if or .Values.env .Values.db.injectEnv .Values.ingress.enabled .Values.envOverride }}
          env:
            {{- if .Values.ingress.enabled }}
            - name: HOSTNAME
              value: {{ .Values.ingress.host }}
            {{- end }}
            {{- if .Values.db.injectEnv }}
            - name: {{ .Values.db.envPrefix }}_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-pg-app
                  key: uri
            - name: {{ .Values.db.envPrefix }}_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-pg-app
                  key: username
            - name: {{ .Values.db.envPrefix }}_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-pg-app
                  key: password
            - name: {{ .Values.db.envPrefix }}_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-pg-app
                  key: host
            - name: {{ .Values.db.envPrefix }}_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-pg-app
                  key: port
            - name: {{ .Values.db.envPrefix }}_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-pg-app
                  key: dbname
            {{- end }}
            {{- if .Values.env }}
            {{- .Values.env | toYaml | nindent 12 }}
            {{- end }}
            {{- if .Values.envOverride }}
            {{- .Values.envOverride | toYaml | nindent 12 }}
            {{- end }}
          {{- end }}
