apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/component: application
        app.kubernetes.io/part-of: {{ .Values.serviceName }}
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ if eq .Values.image.tag "latest" }}Always{{ else }}IfNotPresent{{ end }}
        {{- if .Values.livenessProbe }}
        livenessProbe: {{ .Values.livenessProbe | toYaml | nindent 2 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe: {{ .Values.readinessProbe | toYaml | nindent 2 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.port }}
        {{- if .Values.env }}
        env: {{ .Values.env | toYaml | nindent 2 }}
        {{- end }}
