apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: traefik
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  entryPoints:
   - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.ingress.host }}`)
    services:
      - name: {{ .Release.Name }}
        passHostHeader: true
        port: {{ .Values.port }}
