{{ if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.name }}
  annotations:
    kubernetes.io/ingress.class: traefik
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  entryPoints:
   - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.ingress.host }}`)
    services:
      - name: {{ .Values.name }}
        passHostHeader: true
        port: {{ .Values.port }}
{{ end -}}
