{{- if .Values.postgres.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "app.fullname" . }}-pg
  labels:
    app.kubernetes.io/component: database
  finalizers:
    - cnpg.io/cluster
spec:
  {{- if or .Values.postgres.backup.enabled .Values.postgres.plugins }}
  plugins:
    {{- if .Values.postgres.backup.enabled }}
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      enabled: true
      parameters:
        barmanObjectName: {{ include "app.fullname" . }}-pg-backup
    {{- end }}
    {{- with .Values.postgres.plugins }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- with .Values.postgres.image }}
  imageName: {{ . }}
  {{- end }}
  instances: {{ .Values.postgres.instances }}
  storage:
    size: {{ .Values.postgres.storage.size }}
    storageClass: {{ .Values.postgres.storage.storageClass }}
  {{- if .Values.postgres.bootstrap }}
  bootstrap:
    {{- .Values.postgres.bootstrap | toYaml | nindent 4 }}
  {{- end }}
  {{- if .Values.postgres.managed }}
  managed:
    {{- .Values.postgres.managed | toYaml | nindent 4 }}
  {{- end }}
  {{- if .Values.postgres.postgresql }}
  postgresql:
    {{- .Values.postgres.postgresql | toYaml | nindent 4 }}
  {{- end }}
  monitoring:
    enablePodMonitor: true
  affinity:
    {{- .Values.postgres.affinity | toYaml | nindent 4 }}
{{- end }}
