{{- if and .Values.rabbitmq.secret.replicateFrom .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rabbitmq.secret.name }}
  annotations:
    replicator.v1.mittwald.de/replicate-from: {{ .Values.rabbitmq.secret.replicateFrom }}
data: {}
{{- end }}
