{{- if .Values.rover.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.fullname" . }}-rover
  labels:
    app.kubernetes.io/name: {{ include "app.fullname" . }}-rover
    app.kubernetes.io/component: rover
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app.fullname" . }}-rover
        app.kubernetes.io/component: rover
    spec:
      restartPolicy: Never
      containers:
        - name: rover
          image: alpine:latest
          envFrom:
            - secretRef:
                name: apollo
          command:
            - sh
            - -c
            - |
              apk add --no-cache curl bash
              curl -sSL https://rover.apollo.dev/nix/latest | bash
              export PATH="$HOME/.rover/bin:$PATH"
              rover subgraph introspect http://{{ include "app.fullname" . }}:{{ .Values.service.port }}/graphql | \
              rover subgraph publish {{ .Values.rover.graphRef }} \
                --name {{ include "app.fullname" . }} \
                --schema - \
                --routing-url http://{{ include "app.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.port }}/graphql
{{- end }}
